spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

application:
  jwt:
    expiration: 300000 # 5m
    refresh-expiration: 64800000 # 1d
    secret-key: ${SECRET_KEY}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html